In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=000fc548033af90caafc50d82c455cbd&language=en-US&page=1')

In [3]:
temp_df = pd.DataFrame(response.json()['results'])[['id','adult', 'title','overview','release_date','popularity','vote_average','vote_count']]

In [4]:
temp_df.head()

,id,adult,title,overview,release_date,popularity,vote_average,vote_count
0,278,False,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,45.2043,8.718,30143
1,238,False,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,44.2986,8.686,22775
2,240,False,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.7078,8.571,13800
3,424,False,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,26.6381,8.567,17329
4,389,False,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,19.1015,8.560,9903

In [5]:
partial_dfs = []

for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=000fc548033af90caafc50d82c455cbd&language=en-US&page={}'.format(i))
    partial_df = pd.DataFrame(response.json()['results'])[['id','adult', 'title','overview','release_date','popularity','vote_average','vote_count']]
    partial_dfs.append(partial_df)

df = pd.concat(partial_dfs, ignore_index=True)

In [6]:
df

,id,adult,title,overview,release_date,popularity,vote_average,vote_count
0,278,False,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,45.2043,8.718,30143
1,238,False,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,44.2986,8.686,22775
2,240,False,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.7078,8.571,13800
3,424,False,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,26.6381,8.567,17329
4,389,False,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,19.1015,8.560,9903
...,...,...,...,...,...,...,...,...
8555,531503,False,Point Blank,A nurse is forced to spring a wounded murder s...,2019-07-12,5.6108,5.999,571
8556,442249,False,The First Purge,To push the crime rate below one percent for t...,2018-07-04,7.6337,5.999,4202
8557,340487,False,Certain Women,Three strong-willed women strive to forge thei...,2016-09-25,4.4941,5.999,379
8558,76494,False,What to Expect When You're Expecting,Challenges of impending parenthood turn the li...,2012-05-17,5.8988,5.999,1846
8559,36669,False,Die Another Day,James Bond is sent to investigate the connecti...,2002-11-17,10.4822,5.998,3854

In [7]:
df.shape

(8560, 8)

In [8]:
df.to_csv('movies.csv')