# ML Pipelines

In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [4]:
df = pd.read_csv('train.csv')

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=42)

In [8]:
X_train.head(3)

     Pclass   Sex   Age  SibSp  Parch    Fare Embarked
331       1  male  45.5      0      0  28.500        S
733       2  male  23.0      0      0  13.000        S
382       3  male  32.0      0      0   7.925        S

In [9]:
y_train.head(3)

331    0
733    0
382    0
Name: Survived, dtype: int64

## 1. Manual Implementation of Preprocessing and Training Steps

In [10]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [19]:
# Applying imputation for null values

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [20]:
# OHE -> Sex, and Embarked

ohe_sex = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [24]:
X_train_rem = X_train.drop(columns=['Sex', 'Age', 'Embarked'])
X_test_rem = X_test.drop(columns=['Sex', 'Age', 'Embarked'])

In [26]:
X_train_transformed = np.concatenate((X_train_rem, X_train_age, X_train_sex, X_train_embarked), axis=1)

In [27]:
X_test_transformed = np.concatenate((X_test_rem, X_test_age, X_test_sex, X_test_embarked), axis=1)

In [30]:
X_train_transformed.shape, X_test_transformed.shape

((712, 8), (179, 8))

In [29]:
# Model Training

clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [31]:
y_pred = clf.predict(X_test_transformed)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7877094972067039

### Re-run preprocessors and predict on test input

In [33]:
import pickle

In [37]:
# pickle.dump(ohe_sex, open('models/ohe_sex.pkl', 'wb'))
# pickle.dump(ohe_embarked, open('models/ohe_embarked.pkl', 'wb'))
# pickle.dump(clf, open('models/clf.pkl', 'wb'))

In [38]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [39]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [40]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [41]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [43]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [44]:
test_input_age = test_input[:,2].reshape(1,1)

In [48]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [49]:
test_input_transformed.shape

(1, 8)

In [50]:
clf.predict(test_input_transformed)

array([0])

## 2. Using Pipelines for Preprocessing and Training steps

In [51]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2

In [52]:
df = pd.read_csv('train.csv')

In [53]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=42)

In [56]:
X_train.head(3)

     Pclass   Sex   Age  SibSp  Parch    Fare Embarked
331       1  male  45.5      0      0  28.500        S
733       2  male  23.0      0      0  13.000        S
382       3  male  32.0      0      0   7.925        S

In [61]:
# imputation transformer

trf1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6])
], remainder='passthrough')

In [63]:
# one hot encoding transformer

trf2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output=False,handle_unknown='ignore',drop='first'), [1, 6]),
], remainder='passthrough')

In [64]:
# Scaling

trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(),slice(0,8))
])

In [65]:
# Feature Selection

trf4 = SelectKBest(score_func=chi2, k=5)

In [66]:
# train the model

trf5 = DecisionTreeClassifier()

In [67]:
# Create Pipeline

pipe = Pipeline([
    ('trf1', trf1),
    ('trf2', trf2),
    ('trf3', trf3),
    ('trf4', trf4),
    ('trf5', trf5),
])

**Pipeline Vs make_pipeline**

- Pipeline requires naming of steps, make_pipeline does not.
- (Same applies for ColumnTransformer vs make_column_transformer).

In [68]:
# Alternate Syntax
pipe = make_pipeline(trf1, trf2, trf3, trf4, trf5)

In [69]:
# train
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 8, None))])),
                ('selectkbest',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x000001D7F9141B20>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

### Explore pipeline

In [71]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(drop='first',
                                                handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'columntransformer-3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 8, None))]),
 'selectkbest': SelectKBest(k=5, score_func=<function chi2 at 0x000001D7F9141B20>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [73]:
pipe.named_steps['columntransformer-1'].transformers_

[('impute_age', SimpleImputer(), [2]),
 ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6]),
 ('remainder',
  FunctionTransformer(accept_sparse=True, check_inverse=False,
                      feature_names_out='one-to-one'),
  [0, 1, 3, 4, 5])]

In [74]:
y_pred = pipe.predict(X_test)

D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.5865921787709497

### Cross Validation using Pipeline

In [77]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

np.float64(0.6068354181030238)

In [80]:
import pickle

In [81]:
# pickle.dump(pipe, open('pipe.pkl', 'wb'))

### Re-run pipeline and predict on test input

In [82]:
pipe = pickle.load(open('pipe.pkl', 'rb'))

In [83]:
test_input2 = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [84]:
pipe.predict(test_input2)

D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
D:\github-repos\ml-from-math-to-applications\.env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([0])